site_name: Viadot Docs
nav:
  - Home: home.md
  - Howtos:
      - "Config File": howtos/config_file.md
      - Flows: howtos/flows.md
  - Tutorials:
      - Tutorials: tutorials/placeholder.md
  - References:
      - "SQL Sources": references/sql_sources.md
      - "API Sources": references/api_sources.md
      # - "Task library": references/sources.md
theme:
  name: "material"
  features:
    - navigation.tabs
plugins:
  - search
  - mkdocstrings:
      watch:
        - viadot
      handlers:
        python:
          rendering:
            show_root_heading: yes
dev_addr: "0.0.0.0:8000"
