site_name: Viadot Docs
site_url: "https://dyvenia.github.io/viadot/"
nav:
  - Home: index.md
  - Howtos:
      - "Config File": howtos/config_file.md
      - "Running a task": "howtos/running_tasks.md"
      - Flows: howtos/flows.md 
  - Tutorials: tutorials/adding_source.md
  - Task library: references/task_library.md
  - References:
      - "SQL Sources": references/sql_sources.md
      - "API Sources": references/api_sources.md
theme:
  name: "material"
  features:
    - navigation.tabs
plugins:
  - search
  - mkdocstrings:
      watch:
        - viadot
      handlers:
        python:
          rendering:
            show_root_heading: yes
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
dev_addr: "0.0.0.0:8000"
