name: deploy_docs

on:
  workflow_dispatch:

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 0.1.12
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material mkdocstrings
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: mkdocs gh-deploy --force
