name: deploy_docs

on:
  workflow_dispatch:

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material mkdocstrings azure-core azure-storage-blob azure-keyvault azure-identity adlfs prefect pandas pyarrow pyodbc PyGithub
      - run: mkdocs gh-deploy --force
